<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

    <Version>1.6.0</Version>
    <AssemblyVersion>1.6.0.0</AssemblyVersion>
    <FileVersion>1.6.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="payload.zip" LogicalName="Payload.zip" />
    <EmbeddedResource Include="..\AudioDeviceSwitcher.WinUI\app.ico" LogicalName="app.ico" />
  </ItemGroup>

  <PropertyGroup>
    <ApplicationIcon>..\AudioDeviceSwitcher.WinUI\app.ico</ApplicationIcon>
  </PropertyGroup>

</Project>